### ISSUE TITLE
angularfire.min.js causing error Unknown provider: $firebaseSimpleLoginProvider <- $firebaseSimpleLogin

### ISSUE THREAD

**Issue by quanghoc** [firebase/firebase-angular-starter-pack#6]
I think minify this file causing problem with `firebase-simple-login.js`:

https://github.com/firebase/firebase-angular-starter-pack/blob/master/Ionic-seed/www/js/firebase/angularfire.min.js

```
Error: [$injector:unpr] Unknown provider: $firebaseSimpleLoginProvider <- $firebaseSimpleLogin
http://errors.angularjs.org/1.2.7/$injector/unpr?p0=NaNirebaseSimpleLoginProvider%20%3C-%20%24firebaseSimpleLogin
    at http://0.0.0.0:4001/js/angular/angular.js:78:12
    at http://0.0.0.0:4001/js/angular/angular.js:3540:19
    at Object.getService [as get] (http://0.0.0.0:4001/js/angular/angular.js:3667:39)
    at http://0.0.0.0:4001/js/angular/angular.js:3545:45
    at getService (http://0.0.0.0:4001/js/angular/angular.js:3667:39)
    at invoke (http://0.0.0.0:4001/js/angular/angular.js:3694:13)
    at Object.instantiate (http://0.0.0.0:4001/js/angular/angular.js:3715:23)
    at http://0.0.0.0:4001/js/angular/angular.js:6766:28
    at update (http://0.0.0.0:4001/js/ionic-angular.js:2786:30)
    at directive.link (http://0.0.0.0:4001/js/ionic-angular.js:2749:7) 
```

If I use this version, it is fine
https://github.com/firebase/firebase-angular-starter-pack/blob/master/angularFire-seed/test/lib/firebase/angularfire.js

**Comment by dhawking** [comment]
@designnotdrum 

which methods did you use in place of (login, logout, etc)?

**Comment by designnotdrum** [comment]
@dhawking I used this as my guide: https://www.firebase.com/docs/web/guide/user-auth.html - hope that helps.

**Comment by bthj** [comment]
In case it helps anyone:  After pulling in the latest changes from the angularfire-seed project (up to commit [3d76b5e2ce1a345a2d751f52a1864e29bed72bae](https://github.com/firebase/angularfire-seed/commit/3d76b5e2ce1a345a2d751f52a1864e29bed72bae)) I experienced the same error, even though everything seemed to be migrated to using $firebaseAuth
-> It was not until cleared the browser cache / force-reloaded that the error went away :o)
